'use client';
import {useCallback,useState} from 'react';
import {useDropzone} from 'react-dropzone';
import {PDFDocument,rgb} from 'pdf-lib';
import * as XLSX from 'xlsx';
import JSZip from 'jszip';

const formats=['PDF','PNG','JPG','WEBP','CSV','XLSX'];
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function imageBlob(file,type,quality){const bmp=await createImageBitmap(file),c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;c.getContext('2d').drawImage(bmp,0,0);return await new Promise(r=>c.toBlob(r,type,quality/100))}
async function imagePdf(files){const pdf=await PDFDocument.create();for(const f of files){const b=await imageBlob(f,'image/jpeg',92),bytes=new Uint8Array(await b.arrayBuffer()),im=await pdf.embedJpg(bytes);const p=pdf.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height})}return new Blob([await pdf.save()],{type:'application/pdf'})}
export default function Home(){const [files,setFiles]=useState([]),[out,setOut]=useState('PDF'),[quality,setQuality]=useState(90),[busy,setBusy]=useState(false),[msg,setMsg]=useState('Ready'),[results,setResults]=useState([]),[dark,setDark]=useState(true);
const onDrop=useCallback(fs=>{setFiles(x=>[...x,...fs]);setMsg(`${fs.length} file(s) added`);},[]);const dz=useDropzone({onDrop,multiple:true});
async function convert(){if(!files.length)return setMsg('Please upload files first');setBusy(true);setMsg('Converting…');try{let r=[];if(out==='PDF'&&files.every(f=>f.type.startsWith('image/'))){r.push({name:'merged-images.pdf',blob:await imagePdf(files)})}else if(['PNG','JPG','WEBP'].includes(out)){for(const f of files){if(!f.type.startsWith('image/'))continue;const mime=out==='PNG'?'image/png':out==='JPG'?'image/jpeg':'image/webp';r.push({name:`${f.name.split('.')[0]}.${out.toLowerCase()}`,blob:await imageBlob(f,mime,quality)})}}else if(out==='CSV'||out==='XLSX'){for(const f of files){const text=await f.text();const wb=XLSX.read(text,{type:'string'});if(out==='XLSX')r.push({name:f.name.replace(/\.[^.]+$/,'')+'.xlsx',blob:new Blob([XLSX.write(wb,{bookType:'xlsx',type:'array'})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})});else{const sheet=wb.Sheets[wb.SheetNames[0]];r.push({name:f.name.replace(/\.[^.]+$/,'')+'.csv',blob:new Blob([XLSX.utils.sheet_to_csv(sheet)],{type:'text/csv'})})}}}else{for(const f of files){const text=await f.text();const pdf=await PDFDocument.create();const p=pdf.addPage();p.drawText(text.slice(0,3000),{x:40,y:760,size:10,color:rgb(0,0,0)});r.push({name:f.name.replace(/\.[^.]+$/,'')+'.pdf',blob:new Blob([await pdf.save()],{type:'application/pdf'})})}}setResults(r);setMsg(`${r.length} result(s) ready`);localStorage.setItem('fileforge-log',new Date().toISOString())}catch(e){setMsg('Conversion failed: '+e.message)}finally{setBusy(false)}}
return <main className="min-h-screen p-4 md:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-cyan-300">FILEFORGE</p><h1 className="text-4xl font-bold">Universal File Converter</h1><p className="muted mt-2">Convert files privately in your browser.</p></div><button className="glass px-4 py-2" onClick={()=>setDark(!dark)}>{dark?'Theme':'Theme'}</button></header><section className="glass p-5"><div {...dz.getRootProps()} className="rounded-2xl border-2 border-dashed border-cyan-700 p-10 text-center"><input {...dz.getInputProps()}/><h2 className="text-xl font-semibold">Drop files here</h2><p className="muted my-2">or tap to select multiple files</p><button className="bg-cyan-500 px-5 py-3 font-semibold text-slate-950">Choose Files</button></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label>Output<select value={out} onChange={e=>setOut(e.target.value)} className="mt-2 w-full bg-slate-900 p-3">{formats.map(x=><option key={x}>{x}</option>)}</select></label><label>Quality: {quality}<input type="range" min="1" max="100" value={quality} onChange={e=>setQuality(+e.target.value)} className="mt-4 w-full"/></label><div className="flex items-end"><button disabled={busy} onClick={convert} className="w-full bg-emerald-400 p-3 font-bold text-slate-950 disabled:opacity-50">{busy?'Working…':'Convert Files'}</button></div></div><p className="mt-4 text-cyan-200">{msg}</p></section><section className="glass mt-6 p-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">Selected Files ({files.length})</h2><button onClick={()=>{setFiles([]);setResults([]);setMsg('Cleared')}} className="text-rose-300">Clear</button></div><ul className="mt-3 space-y-2">{files.map((f,i)=><li key={i} className="rounded-xl bg-slate-900 p-3">{f.name} <span className="muted">({Math.round(f.size/1024)} KB)</span></li>)}</ul></section><section className="glass mt-6 p-5"><h2 className="text-xl font-semibold">Downloads</h2>{results.length===0?<p className="muted mt-2">Converted files will appear here.</p>:<div className="mt-3 space-y-2">{results.map((r,i)=><button key={i} onClick={()=>download(r.blob,r.name)} className="mr-2 bg-cyan-500 px-4 py-3 font-semibold text-slate-950">Download {r.name}</button>)}</div>}</section><footer className="muted mt-8 text-center text-sm">Frontend MVP • Client-side processing • Next.js</footer></div></main>}
